name: breeds_recognition
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  device_apps:
  tflite: any
  image_picker: ^0.8.5+3
  tflite_flutter: ^0.5.0
  sprintf: ^4.0.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  build_runner: ^2.1.11
  webview_flutter: ^3.0.4
  flutter_lints: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
